### ISSUE TITLE
Not working with airline

### ISSUE THREAD

**Issue by carlitux** [bagrat/vim-workspace#1]
This is supported?

**Comment by bagrat** [comment]
Hi @carlitux, what exactly does not work? Does the `VimWorkspace` tabline show up? If not, is there anything else in the tabline?

If you are using airline's tabline, than you will need to switch it off, to let `VimWorkspace` appear. The airline tabline is disabled by default, so if you have the following line in your vimrc, just make sure to remove it:

```
let g:airline#extensions#tabline#enabled = 1
```

Please let me know if this works for you, and if not, please answer the questions above.

**Comment by carlitux** [comment]
Now tabline was changed but looks like there is issues with vim-startify and no good support with airline.

**Comment by bagrat** [comment]
@carlitux can you please post some screenshots? Please include as many cases as possible, describing them.

**Comment by carlitux** [comment]
They are the errors but are in Spanish

<img width="1436" alt="screen shot 2017-05-16 at 7 15 47 pm" src="https://cloud.githubusercontent.com/assets/40538/26132178/72f05d0a-3a6c-11e7-8a98-c94e9a132572.png">
<img width="1440" alt="screen shot 2017-05-16 at 7 17 53 pm" src="https://cloud.githubusercontent.com/assets/40538/26132185/7abc6678-3a6c-11e7-8314-915597db2750.png">

**Comment by bagrat** [comment]
@carlitux thanks for the screenshots. I will try to resolve your issue with a bit more info. Can you please update the plugin and see how it works?

If that does not resolve the issue, please link me to your vim config so that I can reproduce your situation locally.

**Comment by carlitux** [comment]
Here is: https://github.com/linkux-it/vimgalaxy
Tabline is not highlighting the current buffer

**Comment by carlitux** [comment]
Also there is an error with denite plugin set_colors function

**Comment by bagrat** [comment]
@carlitux I am currently working on this one. Could you please open a separate issue for the `denite` problem, and provide more details (messages, etc)?

**Comment by bagrat** [comment]
@carlitux pushed a fix https://github.com/bagrat/vim-workspace/commit/9f3fdbadeebac8c8d99db4300d11d5ac5062f6a3 that should fix these issues.

Please verify and let me know if the problems remain.

**Comment by carlitux** [comment]
@bagrat it is looking good, now working... maybe try to use colors from schema? also fixed this https://github.com/bagrat/vim-workspace/issues/4

**Comment by bagrat** [comment]
@carlitux thanks for the verification.

> maybe try to use colors from schema

You mean pick some standard colors from users current colorscheme? If you have any suggestions or feature, (sorry for this bureaucracy) please open a new issue, and let's discuss in that scope, to keep track of things. How does that sound?

**Comment by carlitux** [comment]
With vim startify buffer  still errors
