### ISSUE TITLE
Error after vim-plug finishes installing

### ISSUE THREAD

**Issue by mkraemer** [bagrat/vim-workspace#3]
After running :PlugInstall using vim-plug I'm getting the following error:

    Error detected while processing /home/mkraemer/.local/share/nvim/site/plugged/vim-workspace/plugin/workspace.vim:
    line   73:
    E421: Color name or number not recognized: ctermbg= ctermfg=

This only pops up immediately after vim-plug has finished; after subsequents starts everything seems to work great so far :)

I'm using neovim 0.1.7.

Thanks for the plugin btw. :)

**Comment by bagrat** [comment]
Thanks for using it @mkraemer and for the feedback.

Just tried with `nvim 0.1.7`, but did not get the error. Could you share your configs so I can reproduce?

**Comment by mkraemer** [comment]
Sure :)

https://github.com/mkraemer/dotfiles/blob/master/vim/.config/nvim/init.vim

I had the chance to play around with vim-workspace for a while and spent some time adapting the colors to my workflow. Everything works great, so the error I've encountered after running :PlugInstall seems not to impact anything :)

**Comment by bagrat** [comment]
Thanks for the configs @mkraemer, I was able to reproduce it, and pushed a fix: https://github.com/bagrat/vim-workspace/commit/9f3fdbadeebac8c8d99db4300d11d5ac5062f6a3

Could you please verify that the error is gone? Thanks in advance!

**Comment by mkraemer** [comment]
Yes, fixed for me too :)

Thx :heart:
