### ISSUE TITLE
Denite issue

### ISSUE THREAD

**Issue by carlitux** [bagrat/vim-workspace#4]
```
[denite] neovim.api.nvim.NvimError: b'Vim(call):E117: Unknown function: <SNR>100_set_colors
````

Looks like it is here:

https://github.com/bagrat/vim-workspace/blob/514495914fc361d50b9aaa49c0a888fa50c03834/plugin/workspace.vim#L137

Steps to reproduce:

1. `:Denite buffer` or `:Denite file_rec`
2. Select one item

**Comment by bagrat** [comment]
@carlitux should be fixed with https://github.com/bagrat/vim-workspace/commit/9f3fdbadeebac8c8d99db4300d11d5ac5062f6a3
