### ISSUE TITLE
GVim compatibility 

### ISSUE THREAD

**Issue by joe666** [bagrat/vim-workspace#6]
Hello,

Thank you for your very nice and useful plugin. I am having a hard time making it look under GVim exactly as it looks on terminal vim.

It seems GVim somehow turns each buffer/tab into the colors of the current GTK theme. Any advice or suggestion ?

Using VIM 8.0 

This is the list of my current installed plugins via Pathogen

bufexplorer  
nerdtree  
phpcomplete.vim  
supertab   
tcomment_vim  
ultisnips           
vim-airline  
vim-devicons      
vim-polyglot  
vim-workspace
mru          
pdv       
php.vim          
syntastic  
tlib_vim      
vim-addon-mw-utils  
vim-blade    
vim-php-cs-fixer  
vim-snippets  
vmustache

Thank you again.

**Comment by bagrat** [comment]
@joe666 thanks for the issue and details provided. If you could also attach a screenshot that would be even better. In the meantime, I will try to reproduce what you have described, and get you some updates as ASAP.

**Comment by joe666** [comment]
Thank you very much for the quick response, attached what I am seeing.

![gvim](https://cloud.githubusercontent.com/assets/282958/26223397/8190ca34-3be3-11e7-8156-9031bd07f7ec.png)

Interestingly enough the key mappings work as expected.

**Comment by bagrat** [comment]
@joe666 thanks for the screenshot. I just figured it out.

So gvim shows "GUI tabline" and hides the text tabline, and that is why you see a single tab there, which represents the single tabpage you have.

So disable that, try setting this in your vimrc:

`set guioptions-=e`

Let me know if this works for you.

**Comment by joe666** [comment]
It works, thank you very much for your help and congrats on the excellent plugin.

**Comment by bagrat** [comment]
Glad it worked! Thank you for using the plugin!
