### ISSUE TITLE
WS doesn't replace tabline on MacVim properly

### ISSUE THREAD

**Issue by bakkerme** [bagrat/vim-workspace#7]
If I try to use vim-workspace in the GUI MacVim, rather than getting the workspace tabline I get the GUI tabline. After reading the gvim related issue, I added  `set guioptions -=e` to my .vimrc. However, that only gave me the standard CLI tabline. I can confirm that it's loaded, since the commands offered by the plugin do work. If I use the cli MacVim, everything will work fine, provided I remove the command to turn off the GUI tabline.

I normally use https://github.com/ap/vim-buftabline, which also takes over the tabline and works in MacVim, although it disappears when you create a new tab. It may provide some guidance in implementing a fix.

**Comment by bagrat** [comment]
Thanks for reporting this @bakkerme. I will try to reproduce the case and get back asap.

**Comment by bagrat** [comment]
Hey @bakkerme, sorry for a supper late response.

I have tried to reproduce the issue you have described with MacVim but no success. I will post screenshots.

**After launching MacVim and creating a couple of empty buffers and tabs:**
<img width="817" alt="screen shot 2017-10-05 at 5 53 12 pm" src="https://user-images.githubusercontent.com/3033265/31230941-89c17ed4-a9f6-11e7-922f-929f83af5c1c.png">

As you can see I have default the GUI tabline.

**After running `:set guioptions-=e`:**
<img width="815" alt="screen shot 2017-10-05 at 5 53 34 pm" src="https://user-images.githubusercontent.com/3033265/31230990-a49d1e0c-a9f6-11e7-8515-6bcec0215388.png">

As expected ^

**Comment by bagrat** [comment]
Could you please post the version of MacVim you are using? That might help to progress.

**Comment by bagrat** [comment]
Closing this till I get more feedback and succeed to reproduce.
