### ISSUE TITLE
Garbled output in Vim8 internal terminal.

### ISSUE THREAD

**Issue by chew-z** [bagrat/vim-workspace#9]
I have been using your plugin (which changed the way I use buffers) but I am also avid user of [fzf in Vim](https://github.com/junegunn/fzf.vim) and MacVim. Here is the problem.

Since latest release (ver 17.1) fzf is using internal terminal emulator of Vim to present present results. Before in MacVim you had to use a glue script and see results in external terminal window. So this is change for good.

I have noticed however that my output in Vim internal terminal is garbled when using fzf. Like in [this issue ](https://github.com/junegunn/fzf.vim/issues/470#issuecomment-338385104).

After some trials I have found that the reason is tabs shown by vim-workspace in MacVim. Somehow they are fouling terminal. When I set `set guioptions-=e` I am back to MacVim tabs which is a pity but all the artefacts within Terminal window are gone. 

<img width="847" alt="screen shot 2017-10-21 at 18 00 42" src="https://user-images.githubusercontent.com/2264679/31851752-380416e0-b696-11e7-88b0-35141c38823f.png">

**Comment by bagrat** [comment]
Hey @chew-z, I see you closed the issue, was it a wrong call or you found a fix?

Please let me know if I can help and thanks for using the plugin!

**Comment by chew-z** [comment]
Yes, it might be that adding tabs from vim-workspace fool MacVim/Vim terminal but I am just not sure. I just cannot isolate the problem well enough. So please disregard this issue.

**Comment by semanser** [comment]
I get this problem without vim-workspace, so the problem is probably in the fzf.vim itself.
